# Supplementary figure -- hammock's subB speedup as a function of N (files
# per side), p=18, jaccard_similarity_ie arm throughout.
#
# See docs/seed-subsampling-synthetic-supplement.md for why this exists: the
# outline's original synthetic-corpus subB claim ("4.21x at p=14") never
# traced to any real measurement at any precision. This replaces it with a
# real one, generated by experiments/bedtools_benchmark/sbatch_subB_nsweep.sh
# (job 29758041) via benchmark_cpp_vs_bedtools.py's new --metrics-all flag.
#
# HAMMOCK-ONLY, NO PROJECTED BEDTOOLS LINE. A prior design considered a
# projected bedtools reference (the plot_largeN_supplement.R technique), but
# a reviewer's argument won out: one projected bedtools curve under THREE
# hammock curves (one per subB) lets a reader compute three different
# "hammock vs bedtools" speedups from a single unmeasured extrapolation, for
# zero new bedtools information (bedtools' wall time does not depend on subB
# at all, so the fitted curve would be numerically identical to the one
# Figure S7 already publishes). This figure answers a narrower question
# instead: how does subB's OWN benefit change with scale.
#
# PREDICTION STATED BEFORE MEASURING (both plan-review agents independently
# derived this, so it's recorded here rather than fit post hoc): subB only
# discounts the Theta(N) sketch-construction phase; the Theta(N^2)
# pairwise-comparison phase (which --metrics makes costlier) is
# subB-invariant and its share of total wall time grows fast with N. So the
# three subB lines in Panel A should NARROW toward each other as N -> 2048,
# not stay parallel on the log-log plot. Panel B (sketch-time-only) and
# Panel D (comparison-time share) exist specifically to show WHY, by
# isolating the component subB actually touches from the one it doesn't.
#
# Panel C (peak RSS) exists because it was asked for explicitly, even though
# no strong effect is expected: subB changes how many points get inserted
# into a sketch, not the sketch's size (fixed at 2^precision registers), so
# RSS should be ~flat across subB at fixed N. If it isn't, that's worth
# knowing.
#
# OVERLAP SANITY CHECK. This job is a single allocation end-to-end (not
# stitched across two SLURM jobs the way the large-N supplement is), so the
# two-allocation overlap-check machinery in plot_largeN_supplement.R does not
# strictly apply -- but checking this job's own subB=1.0 arm at N=512 against
# the already-published, separately-allocated Figure 3A point
# (docs/data/cpp_vs_bedtools_t16_p18.csv) is a free correctness check, so it's
# done below and printed, not silently skipped.

required_packages <- c("dplyr", "readr", "ggplot2", "scales", "patchwork", "Cairo", "tidyr")
missing_packages <- required_packages[
  !vapply(required_packages, requireNamespace, logical(1), quietly = TRUE)
]
if (length(missing_packages) > 0) {
  stop("Missing required R packages: ", paste(missing_packages, collapse = ", "),
       "\nInstall them before running this script.", call. = FALSE)
}

suppressPackageStartupMessages({
  library(dplyr); library(readr); library(ggplot2)
  library(scales); library(patchwork); library(Cairo); library(tidyr)
})

script_arg <- grep("^--file=", commandArgs(trailingOnly = FALSE), value = TRUE)
if (length(script_arg) != 1) stop("Run with Rscript.", call. = FALSE)
script_dir <- dirname(normalizePath(sub("^--file=", "", script_arg), mustWork = TRUE))
repo_root <- normalizePath(file.path(script_dir, "..", ".."), mustWork = TRUE)

argv <- commandArgs(trailingOnly = TRUE)
nsweep_csv <- if (length(argv) >= 1) argv[1] else
  Sys.glob(file.path(repo_root, "experiments", "bedtools_benchmark", "results",
                      "cpp_vs_bedtools_t16_*.csv")) %>%
  # Excludes *_runs.csv (per-replicate raw rows, a sibling file
  # benchmark_cpp_vs_bedtools.py writes right after the aggregate CSV on
  # every checkpoint -- see run_benchmark's checkpoint_cb). It matches this
  # same glob and, since it's written second, always has a later mtime, so
  # "most recent by mtime" without this filter silently picks the
  # runs-schema file (no mean_wall_time column) instead of the aggregate one
  # this script actually needs.
  { .[!grepl("_runs\\.csv$", .)] } %>%
  { .[order(file.info(.)$mtime, decreasing = TRUE)][1] }
panelA_csv <- if (length(argv) >= 2) argv[2] else
  file.path(repo_root, "docs", "data", "cpp_vs_bedtools_t16_p18.csv")
out_png <- if (length(argv) >= 3) argv[3] else
  file.path(repo_root, "paper", "figures", "subB_nscaling_supplement.png")

if (is.na(nsweep_csv) || length(nsweep_csv) == 0 || !file.exists(nsweep_csv)) {
  stop("Could not find an N-sweep CSV. Pass its path explicitly as arg 1.", call. = FALSE)
}
if (!file.exists(panelA_csv)) stop("Not found: ", panelA_csv, call. = FALSE)

dir.create(dirname(out_png), recursive = TRUE, showWarnings = FALSE)

COL_1  <- "#007C83"  # subB=1.0   (matches COL_HAMMOCK elsewhere)
COL_01 <- "#D28B35"  # subB=0.1
COL_001<- "#9B4D9B"  # subB=0.01
COL_GRID <- "#D9DEE3"
COL_TEXT <- "#20262D"

theme_paper <- function(base_size = 10.5) {
  theme_classic(base_size = base_size, base_family = "sans") +
    theme(
      plot.title = element_text(face = "bold", size = rel(1.02), color = COL_TEXT,
                                 lineheight = 1.05, margin = margin(b = 4)),
      axis.title = element_text(color = COL_TEXT),
      axis.text = element_text(color = COL_TEXT),
      axis.line = element_line(color = "#6B747D", linewidth = 0.35),
      axis.ticks = element_line(color = "#6B747D", linewidth = 0.35),
      panel.grid.major.y = element_line(color = COL_GRID, linewidth = 0.35),
      panel.grid.minor = element_blank(),
      legend.title = element_blank(),
      legend.text = element_text(size = rel(0.8), color = COL_TEXT),
      legend.position = "bottom",
      plot.margin = margin(6, 8, 6, 6)
    )
}

subb_pal <- c("subB=1.0" = COL_1, "subB=0.1" = COL_01, "subB=0.01" = COL_001)

# --- load and tidy the N-sweep ---------------------------------------------
raw <- read_csv(nsweep_csv, show_col_types = FALSE)

expected_tools <- c("hammock_ie_B", "hammock_ie_B_subB0.1", "hammock_ie_B_subB0.01")
present <- expected_tools %in% raw$tool
if (!all(present)) {
  stop("Missing expected tool(s) in ", basename(nsweep_csv), ": ",
       paste(expected_tools[!present], collapse = ", "),
       " -- was this generated with --metrics-all --subB-list 1.0,0.1,0.01?",
       call. = FALSE)
}

subb_label <- function(sub_b) paste0("subB=", format(sub_b, trim = TRUE))

d <- raw %>%
  filter(tool %in% expected_tools) %>%
  transmute(
    num_files, threads = num_threads, precision, sub_b,
    subb = factor(subb_label(sub_b), levels = c("subB=1.0", "subB=0.1", "subB=0.01")),
    wall_time = mean_wall_time, wall_sd = std_wall_time,
    sketch_time = mean_sketch_creation_time,
    comparison_time = mean_comparison_time,
    rss_mb = mean_max_rss_mb
  ) %>%
  arrange(subb, num_files)

if (any(is.na(d$wall_time))) {
  stop("NA wall_time in the N-sweep CSV -- an incomplete run made it into ",
       "the aggregate (check for a cancelled/partial job).", call. = FALSE)
}

# --- overlap sanity check vs the separately-allocated Figure 3A point ------
panelA <- read_csv(panelA_csv, show_col_types = FALSE) %>%
  filter(tool == "hammock_ie_B", num_files == 512) %>%
  pull(mean_wall_time)

this_512 <- d %>% filter(subb == "subB=1.0", num_files == 512) %>% pull(wall_time)

if (length(panelA) == 1 && length(this_512) == 1) {
  ratio <- this_512 / panelA
  cat(sprintf(
    "Overlap check at N=512, subB=1.0: this job %.3fs vs Figure 3A %.3fs (ratio %.3f)\n",
    this_512, panelA, ratio))
  if (abs(log(ratio)) > log(1.25)) {
    cat("*** WARNING: >25% disagreement with the separately-allocated Figure 3A ",
        "point at N=512. This job's numbers may not be comparable to the rest ",
        "of the paper -- investigate before publishing this figure.\n", sep = "")
  } else {
    cat(sprintf("Within %.1f%% -- consistent with Figure 3A; join OK.\n\n",
                100 * (exp(abs(log(ratio))) - 1)))
  }
} else {
  cat("*** Could not run the overlap check (no N=512 row in one of the two CSVs).\n\n")
}

# --- Panel A: total wall time ------------------------------------------------
pA <- ggplot(d, aes(num_files, wall_time, color = subb)) +
  geom_line(linewidth = 0.9) +
  geom_point(size = 1.6) +
  scale_x_log10(labels = label_number()) +
  scale_y_log10(labels = label_number()) +
  scale_color_manual(values = subb_pal) +
  labs(title = "A. Total wall time (jaccard_similarity_ie arm)",
       x = "N files per side", y = "wall time (s)") +
  theme_paper()

# --- Panel B: sketch-construction time only (the component subB touches) ---
pB <- ggplot(d, aes(num_files, sketch_time, color = subb)) +
  geom_line(linewidth = 0.9) +
  geom_point(size = 1.6) +
  scale_x_log10(labels = label_number()) +
  scale_y_log10(labels = label_number()) +
  scale_color_manual(values = subb_pal) +
  labs(title = "B. Sketch-construction time only",
       x = "N files per side", y = "sketch time (s)") +
  theme_paper()

# --- Panel C: peak RSS -------------------------------------------------------
pC <- ggplot(d, aes(num_files, rss_mb, color = subb)) +
  geom_line(linewidth = 0.9) +
  geom_point(size = 1.6) +
  scale_x_log10(labels = label_number()) +
  scale_y_log10(labels = label_number()) +
  scale_color_manual(values = subb_pal) +
  labs(title = "C. Peak RSS (expected ~flat across subB: sketch size is\nfixed at 2^precision registers, independent of subB)",
       x = "N files per side", y = "peak RSS (MB)") +
  theme_paper()

# --- Panel D: comparison-phase share of wall time, subB-invariant ----------
# The mechanism panel: shows why Panel A's lines should narrow. comparison_time
# is not expected to differ by subB (it operates on already-built sketches), so
# this is plotted once, not per-subB -- three near-identical lines would just
# be visual noise around measurement error.
d_share <- d %>%
  mutate(comparison_share = comparison_time / wall_time) %>%
  filter(subb == "subB=1.0")  # representative; subB-invariant by construction

pD <- ggplot(d_share, aes(num_files, comparison_share)) +
  geom_line(linewidth = 0.9, color = COL_TEXT) +
  geom_point(size = 1.6, color = COL_TEXT) +
  scale_x_log10(labels = label_number()) +
  scale_y_continuous(labels = label_percent()) +
  labs(title = "D. Pairwise-comparison phase as a share of total wall\ntime (subB-invariant -- shown once)",
       x = "N files per side", y = "comparison_time / wall_time") +
  theme_paper()

combined <- (pA + pB) / (pC + pD) +
  plot_annotation(
    title = "Supplementary Figure -- subB speedup vs catalog scale (synthetic corpus, p=18)",
    caption = paste0(
      "mixed-stride method, 10,000 intervals/file, 16 threads, 5 replicates. ",
      "hammock-cpp binary, --metrics-all (jaccard_similarity_ie arm). ",
      "No bedtools reference line: see header comment for why."),
    theme = theme(plot.title = element_text(face = "bold", size = rel(1.1)),
                  plot.caption = element_text(size = rel(0.75), color = COL_TEXT, hjust = 0))
  )

CairoPNG(out_png, width = 11, height = 8.5, units = "in", res = 300)
print(combined)
dev.off()

cat("wrote", out_png, "\n\n")

# --- narrowing check: print the actual ratio between subB=1.0 and subB=0.01
# wall time at the smallest and largest measured N, since that's the concrete
# claim the header predicts. ---
wide <- d %>% select(num_files, subb, wall_time) %>%
  pivot_wider(names_from = subb, values_from = wall_time)
wide$ratio_1_to_001 <- wide[["subB=1.0"]] / wide[["subB=0.01"]]
cat("subB=1.0 / subB=0.01 wall-time ratio by N (narrowing check):\n")
print(as.data.frame(wide[, c("num_files", "ratio_1_to_001")]), row.names = FALSE)
