#!/usr/bin/env Rscript

# Stack the p=12, p=18, and p=24 biological-optimum dendrogram panels into a
# single supplementary figure. The component panels are generated by
# plot_sequence_tissue_clustering.R with panel labels A, B, and C.

required_packages <- c("png", "grid", "Cairo")
missing_packages <- required_packages[
  !vapply(required_packages, requireNamespace, logical(1), quietly = TRUE)
]
if (length(missing_packages) > 0) {
  stop("Missing required R packages: ", paste(missing_packages, collapse = ", "),
       call. = FALSE)
}

script_arg <- grep("^--file=", commandArgs(trailingOnly = FALSE), value = TRUE)
script_path <- sub("^--file=", "", script_arg)
script_dir <- dirname(normalizePath(script_path, mustWork = TRUE))
repo_root <- normalizePath(file.path(script_dir, "..", ".."), mustWork = TRUE)

argv <- commandArgs(trailingOnly = TRUE)
default_inputs <- file.path(
  repo_root, "paper", "figures",
  paste0("sequence_tissue_clustering_bio_p", c(12, 18, 24), ".png")
)
inputs <- if (length(argv) >= 3) argv[1:3] else default_inputs
output <- if (length(argv) >= 4) argv[4] else file.path(
  repo_root, "paper", "figures", "sequence_tissue_clustering_precision.png"
)

missing_inputs <- inputs[!file.exists(inputs)]
if (length(missing_inputs) > 0) {
  stop("Input file(s) not found: ", paste(missing_inputs, collapse = ", "),
       call. = FALSE)
}

panels <- lapply(inputs, png::readPNG)
panel_dims <- vapply(panels, function(x) paste(dim(x)[1:2], collapse = "x"), character(1))
if (length(unique(panel_dims)) != 1) {
  stop("Component panels must have identical pixel dimensions.", call. = FALSE)
}

dir.create(dirname(output), recursive = TRUE, showWarnings = FALSE)
Cairo::CairoPNG(output, width = 3300, height = 5400, bg = "white")
grid::grid.newpage()
grid::pushViewport(grid::viewport(layout = grid::grid.layout(3, 1)))
for (i in seq_along(panels)) {
  grid::grid.raster(
    panels[[i]], interpolate = FALSE,
    vp = grid::viewport(layout.pos.row = i, layout.pos.col = 1)
  )
}
grDevices::dev.off()

message("Wrote: ", output)
