[package]
name = "rust_hll"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_hll"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.19.0", features = ["extension-module"] }
rand = "0.8.5"
num_cpus = "1.16.0" 